name: Build and Deploy Web

on:
  workflow_dispatch:  # Permite execução manual

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Personal Access Token
        run: |
          python -c "
          import os
          import requests

          token = os.getenv('pat')
          if not token:
              print('PERSONAL_ACCESS_TOKEN não configurado.')
          else:
              response = requests.get('https://api.github.com/user', headers={'Authorization': f'token {token}'})
              print('Status Code:', response.status_code)
              print('Response:', response.json())
          "
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
